// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: proto/speed.proto

package SpeedTest

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SpeedTestClient is the client API for SpeedTest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpeedTestClient interface {
	Upload(ctx context.Context, opts ...grpc.CallOption) (SpeedTest_UploadClient, error)
	Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (SpeedTest_DownloadClient, error)
}

type speedTestClient struct {
	cc grpc.ClientConnInterface
}

func NewSpeedTestClient(cc grpc.ClientConnInterface) SpeedTestClient {
	return &speedTestClient{cc}
}

func (c *speedTestClient) Upload(ctx context.Context, opts ...grpc.CallOption) (SpeedTest_UploadClient, error) {
	stream, err := c.cc.NewStream(ctx, &SpeedTest_ServiceDesc.Streams[0], "/speedtest.SpeedTest/Upload", opts...)
	if err != nil {
		return nil, err
	}
	x := &speedTestUploadClient{stream}
	return x, nil
}

type SpeedTest_UploadClient interface {
	Send(*UploadRequest) error
	CloseAndRecv() (*UploadResponse, error)
	grpc.ClientStream
}

type speedTestUploadClient struct {
	grpc.ClientStream
}

func (x *speedTestUploadClient) Send(m *UploadRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *speedTestUploadClient) CloseAndRecv() (*UploadResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *speedTestClient) Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (SpeedTest_DownloadClient, error) {
	stream, err := c.cc.NewStream(ctx, &SpeedTest_ServiceDesc.Streams[1], "/speedtest.SpeedTest/Download", opts...)
	if err != nil {
		return nil, err
	}
	x := &speedTestDownloadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SpeedTest_DownloadClient interface {
	Recv() (*DownloadResponse, error)
	grpc.ClientStream
}

type speedTestDownloadClient struct {
	grpc.ClientStream
}

func (x *speedTestDownloadClient) Recv() (*DownloadResponse, error) {
	m := new(DownloadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SpeedTestServer is the server API for SpeedTest service.
// All implementations must embed UnimplementedSpeedTestServer
// for forward compatibility
type SpeedTestServer interface {
	Upload(SpeedTest_UploadServer) error
	Download(*DownloadRequest, SpeedTest_DownloadServer) error
	mustEmbedUnimplementedSpeedTestServer()
}

// UnimplementedSpeedTestServer must be embedded to have forward compatible implementations.
type UnimplementedSpeedTestServer struct {
}

func (UnimplementedSpeedTestServer) Upload(SpeedTest_UploadServer) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedSpeedTestServer) Download(*DownloadRequest, SpeedTest_DownloadServer) error {
	return status.Errorf(codes.Unimplemented, "method Download not implemented")
}
func (UnimplementedSpeedTestServer) mustEmbedUnimplementedSpeedTestServer() {}

// UnsafeSpeedTestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpeedTestServer will
// result in compilation errors.
type UnsafeSpeedTestServer interface {
	mustEmbedUnimplementedSpeedTestServer()
}

func RegisterSpeedTestServer(s grpc.ServiceRegistrar, srv SpeedTestServer) {
	s.RegisterService(&SpeedTest_ServiceDesc, srv)
}

func _SpeedTest_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SpeedTestServer).Upload(&speedTestUploadServer{stream})
}

type SpeedTest_UploadServer interface {
	SendAndClose(*UploadResponse) error
	Recv() (*UploadRequest, error)
	grpc.ServerStream
}

type speedTestUploadServer struct {
	grpc.ServerStream
}

func (x *speedTestUploadServer) SendAndClose(m *UploadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *speedTestUploadServer) Recv() (*UploadRequest, error) {
	m := new(UploadRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SpeedTest_Download_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SpeedTestServer).Download(m, &speedTestDownloadServer{stream})
}

type SpeedTest_DownloadServer interface {
	Send(*DownloadResponse) error
	grpc.ServerStream
}

type speedTestDownloadServer struct {
	grpc.ServerStream
}

func (x *speedTestDownloadServer) Send(m *DownloadResponse) error {
	return x.ServerStream.SendMsg(m)
}

// SpeedTest_ServiceDesc is the grpc.ServiceDesc for SpeedTest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpeedTest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "speedtest.SpeedTest",
	HandlerType: (*SpeedTestServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _SpeedTest_Upload_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Download",
			Handler:       _SpeedTest_Download_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/speed.proto",
}
